#!/bin/bash

#V0.5

if [ -s pi_project_lib ]; then
	. pi_project_lib
elif [ -s `dirname $0`/pi_project_lib ]; then
	. `dirname $0`/pi_project_lib
else
	echo "pi_project_lib not found, exiting."
	exit 1
fi

status '======== Package install/update/removal - may take a while'
require_util pip3 2>/dev/null							|| install_packages python3-pip		#Needed to install and upgrade python packages
require_util i2cdetect 2>/dev/null						|| install_packages i2c-tools		#Needed to detect i2c screen
[ -x /usr/bin/sdl-config ]							|| install_packages libsdl1.2-dev	#Needed for python package updates
[ -f /usr/include/arm-linux-gnueabihf/ffi.h ]					|| install_packages libffi-dev		#Needed for python package updates
[ -f /usr/include/openssl/opensslv.h ]						|| install_packages libssl-dev		#Needed for python package updates
wtg

patch_os
wtg

$SUDO apt-get -y remove claws-mail claws-mail-i18n \
libreoffice libreoffice-avmedia-backend-gstreamer libreoffice-base libreoffice-base-core libreoffice-base-drivers \
libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gtk libreoffice-gtk2 libreoffice-help-en-gb \
libreoffice-impress libreoffice-java-common libreoffice-l10n-en-gb libreoffice-librelogo libreoffice-math libreoffice-nlpsolver \
libreoffice-ogltrans libreoffice-pdfimport libreoffice-pi libreoffice-report-builder libreoffice-report-builder-bin \
libreoffice-script-provider-bsh libreoffice-script-provider-js libreoffice-script-provider-python libreoffice-sdbc-hsqldb \
libreoffice-sdbc-postgresql libreoffice-style-galaxy libreoffice-style-tango libreoffice-systray libreoffice-wiki-publisher \
libreoffice-writer \
minecraft-pi \
vlc vlc-bin vlc-data vlc-l10n vlc-plugin-base vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba vlc-plugin-skins2 \
vlc-plugin-video-output vlc-plugin-video-splitter vlc-plugin-visualization \
wolfram-engine wolframscript
wtg

$SUDO pip3 install RPI.GPIO
$SUDO pip3 install Adafruit-Blinka
$SUDO pip3 install adafruit-circuitpython-ssd1306

install_packages Adafruit-Blinka adafruit-circuitpython-ssd1306 apg bro broctl curl feh fonts-dejavu-core gxmessage lshw python3-numpy python3-pil rpi-eeprom rpi-eeprom-images rsync spi-tools screen spidev tcpdump uhubctl wget x11-utils xorg-x11-apps
wtg

require_util $SUDO chmod chown curl grep mkdir pip3 sed tee touch || fail "A required utility is not installed."
wtg

status '======== File-level changes'
$SUDO mkdir -p /var/toshow/ /usr/local/bin/ /home/pic/
$SUDO chown -R pi.pi /var/toshow/ /home/pic/
wtg

append_if_missing /etc/modules 'i2c-dev'
append_if_missing /etc/modules 'spi-dev'
append_if_missing /boot/config.txt 'dtparam=i2c_arm=on'
append_if_missing /boot/config.txt 'dtparam=spi=on'
append_if_missing /etc/sysctl.conf '#Added by prep_pi_sensor'
append_if_missing /etc/sysctl.conf 'net.ipv6.conf.all.forwarding=0'		#Do not forward packets/act as a router between the interfaces
append_if_missing /etc/sysctl.conf 'net.ipv6.conf.eth0.disable_ipv6=1'
append_if_missing /etc/dhcpcd.conf 'denyinterfaces eth0'			#Do not assign an IP address to the sniffing interface

if grep -q '^iface eth0' /etc/network/interfaces ; then
	echo 'WARNING: There is already a section for "iface eth0" in /etc/network/interfaces.  Appending the correct lines to use, commented out.  Please disable the old block and uncomment the new lines.'
	echo -e '\n#New configuration block; comment out the old eth0 configuration above and uncomment the folling lines when done.\n#auto eth0\n#iface eth0 inet manual\n	#up ifconfig eth0 0.0.0.0 up\n	#up ip link set eth0 promisc on\n	#down ip link set eth0 promisc off\n	#down ip link set eth0 down\n' | $SUDO tee -a /etc/network/interfaces >/dev/null
	echo 'Press enter when ready to edit /etc/network/interfaces'
	read JUNK
	$SUDO vim /etc/network/interfaces
else
	echo -e '\nauto eth0\niface eth0 inet manual\n	up ifconfig eth0 0.0.0.0 up\n	up ip link set eth0 promisc on\n	down ip link set eth0 promisc off\n	down ip link set eth0 down\n' | $SUDO tee -a /etc/network/interfaces >/dev/null
fi


require_util update-rc.d 2>/dev/null						|| install_packages init-system-helpers
install_file https://raw.githubusercontent.com/activecm/pi_show/master/pi_show.py /usr/local/bin/pi_show.py
[ -x /usr/local/bin/pi_show.py ]						|| $SUDO chmod 755 /usr/local/bin/pi_show.py

#FIXME - test for python3.8, then python3.7....
[ -d /usr/local/lib/python3.7/dist-packages/waveshare_epd/ ]			|| $SUDO mkdir /usr/local/lib/python3.7/dist-packages/waveshare_epd/

install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epdconfig.py /usr/local/lib/python3.7/dist-packages/waveshare_epd/epdconfig.py
#FIXME - later copy all display drivers
#Note: "epd2in7b.py" is for the 3 color display
install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epd2in7.py /usr/local/lib/python3.7/dist-packages/waveshare_epd/epd2in7.py

install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/examples/epd_2in7_test.py /home/pi/epd_2in7_test.py
install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/pic/Font.ttc /home/pic/Font.ttc
install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/pic/2in7.bmp /home/pic/2in7.bmp
install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/pic/100x100.bmp /home/pic/100x100.bmp
install_file https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/pic/2in7_Scale.bmp /home/pic/2in7_Scale.bmp

$SUDO chown root.root /usr/local/bin/pi_show.py /usr/local/lib/python3.7/dist-packages/waveshare_epd/  /usr/local/lib/python3.7/dist-packages/waveshare_epd/epdconfig.py /usr/local/lib/python3.7/dist-packages/waveshare_epd/epd2in7.py

$SUDO rm -f /etc/rc.local.new
$SUDO cat /etc/rc.local | grep -v '^exit 0$' | $SUDO tee /etc/rc.local.new >/dev/null
append_if_missing /etc/rc.local.new 'rm -f /tmp/internet_live /var/toshow/[0-9][0-9]*.txt'
append_if_missing /etc/rc.local.new '#ethtool command to reduce processing at eth0'
append_if_missing /etc/rc.local.new 'ethtool -K eth0 gro off lro off rx off tx off gso off'
append_if_missing /etc/rc.local.new 'mkdir -p /opt/bro/pcaps'
#CHECKME - make sure this string gets placed correctly and special characters in the bpf are not screwed up.
append_if_missing /etc/rc.local.new 'screen -S capture -t capture -d -m bash -c nice -n 15 tcpdump -i eth0 -G 3600 -w /opt/bro/pcaps/`hostname -s`.%Y%m%d%H%M%S.pcap -z bzip2 "((tcp[13] & 0x17 != 0x10) or not tcp) and (port 53 or not ((src net 10.0.0.0/8 or src net 172.16.0.0/12 or src net 192.168.0.0/16 or src net 169.254.0.0/16) and (dst net 10.0.0.0/8 or dst net 172.16.0.0/12 or dst net 192.168.0.0/16 or dst net 169.254.0.0/16)) )"'
append_if_missing /etc/rc.local.new '/usr/bin/broctl deploy'
append_if_missing /etc/rc.local.new '/usr/local/bin/pi_show.py >/tmp/pi_show.out 2>&1 &'
append_if_missing /etc/rc.local.new 'exit 0'
$SUDO mv /etc/rc.local /etc/rc.local.backup
$SUDO mv /etc/rc.local.new /etc/rc.local
$SUDO chown root.root /etc/rc.local
$SUDO chmod 755 /etc/rc.local


if [ ! -e /usr/local/bin/message_xfer ]; then
	append_if_missing /usr/local/bin/message_xfer '#!/bin/bash'
	$SUDO chown root.root /usr/local/bin/message_xfer
	$SUDO chmod 755 /usr/local/bin/message_xfer
fi

$SUDO touch /boot/ssh
$SUDO update-rc.d ssh enable
wtg

status '======== Set up ssh keys'
if [ ! -e "$HOME/.ssh/id_rsa_messagexfer" -o ! -e "$HOME/.ssh/id_rsa_messagexfer.pub" ]; then
	echo "Generating a new ssh keypair"
	ssh-keygen -b 2048 -t rsa -N '' -f "$HOME/.ssh/id_rsa_messagexfer"
fi

cmd_out=''
while [ "$cmd_out" != "Success" ]; do
	echo "Please enter the computer name or IP address on which the logs are found:"
	read message_system
	echo "Please enter the user account on that system to which we ssh:"
	read message_user
	echo "Please enter the directory containing the messages: (starting from the root)"
	read message_path
	echo "About to connect to $message_user on $message_system .  If asked to confirm ssh host key, please do so.  You'll be asked for the password for that user on that system."

	cat ~/.ssh/id_rsa_messagexfer.pub 2>/dev/null \
	 | ssh "${message_user}@${message_system}" 'mkdir -p .ssh ; cat >>.ssh/authorized_keys ; chmod go-rwx ./ .ssh/ .ssh/authorized_keys'

	cmd_out=`ssh -o 'PasswordAuthentication=no' -o 'PreferredAuthentications=publickey' -i "$HOME/.ssh/id_rsa_messagexfer" "${message_user}@${message_system}" 'touch .ssh/reached-by-key ; echo Success'`
	if [ "$cmd_out" = "Success" ]; then
		append_if_missing /etc/cron.d/message_xfer '*/5 * * * * pi /usr/local/bin/message_xfer'
		append_if_missing /usr/local/bin/message_xfer "/usr/bin/rsync -av --delete --exclude '00*' -T /var/tmp/ -e 'ssh -i $HOME/.ssh/id_rsa_messagexfer' ${message_user}@${message_system}:${message_path}/ /var/toshow/"
		$SUDO service cron reload
	else
		echo "Unable to ssh to ${message_user}@${message_system} with the ssh keys.  Trying again." >&2
	fi
done
wtg

sync
sleep 1
sync
sleep 1
echo 'About to reboot, press enter to reboot or Ctrl-c to abort.  Note, you must reboot before all settings are active.'
read JUNK
$SUDO reboot

